### ISSUE TITLE
make_more_helpers.sh - Wrong line endings

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#11]
I get the following error:

/Users/hugues/Library/Developer/Xcode/DerivedData/cefWork-carjkkawkrcpkearivwvoqsyhues/Build/Intermediates/cefWork.build/Release/cefWork.build/Script-FD4AF9491A58389A0054EB33.sh: /Users/hugues/Development/openFrameworks/apps/myApps/cefWork/bin/../make_more_helpers.sh: /bin/bash^M: bad interpreter: No such file or directory
/Users/hugues/Library/Developer/Xcode/DerivedData/cefWork-carjkkawkrcpkearivwvoqsyhues/Build/Intermediates/cefWork.build/Release/cefWork.build/Script-FD4AF9491A58389A0054EB33.sh: line 2: /Users/hugues/Development/openFrameworks/apps/myApps/cefWork/bin/../make_more_helpers.sh: Undefined error: 0

It seems to be linked to the line endings used by the .sh script. 
I fixed the issue by opening the .sh with Sublime Text and by changing the line ending to Unix (instead of Windows).

**Comment by ofZach** [comment]
oh thanks, that file is ripped from the binary distribution of CEF, will see about changing it in the repo now....

**Comment by smallfly** [comment]
No sure the issue is completely fixed as I'm now getting the following error: env: python\r: No such file or directory

**Comment by ofZach** [comment]
I just pushed new changes and .gitattributes file to help force line endings, can you try this now?...

**Comment by smallfly** [comment]
All seems to be done now. Thanks.
