### ISSUE TITLE
Handle events between OF and JS (both ways).

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#13]
Hi,

I'm trying to implement a way to enable the communication between the OF app and the loaded JS. I'm looking at the CEF [documentation](https://code.google.com/p/chromiumembedded/wiki/JavaScriptIntegration#Functions_and_Window_Binding), the way it's implemented in [ofxCEFClient](https://github.com/ddiakopoulos/ofxCEFClient/blob/master/src/client/client_app.cpp) and how it's done in [CEF3SimpleSample](https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/Independente/ClientApp.cpp).

I have not good enough understanding of CEF still to determine where this should be done in cefWork. 

Should it be implemented in the class 'Cefgui' or a 'ClientApp' class should be created (as in [ofxCEFClient](https://github.com/ddiakopoulos/ofxCEFClient/blob/master/src/client/client_app.cpp) and [CEF3SimpleSample](https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/Independente/ClientApp.cpp)) ?

Thanks

**Comment by ofZach** [comment]
let me take a look, at least in terms of OF to JS communication, that's been done: 

    if (key == ' '){
        cefgui->executeJS("alert(\"hi\")");
    }

JS -> OF is more complicated, as I recall you have to regster a callback on both the C++ and JS side.  let me take a look, I've done this before with CEF and it wasn't too hard.  lots of info here, btw:  

https://code.google.com/p/chromiumembedded/wiki/JavaScriptIntegration

**Comment by smallfly** [comment]
For the JS -> OF, I see that JS can be injected into the loaded content. "CEF exposes a global JS object with several methods called `app`" (from the ofxCEFClient [readme](https://github.com/ddiakopoulos/ofxCEFClient)). This is what is done in the following `ClientApp` classes (in [ofxCEFClient](https://github.com/ddiakopoulos/ofxCEFClient/blob/master/src/client/client_app.cpp) and [CEF3SimpleSample](https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/Independente/ClientApp.cpp)).

The thing is to get this virtual function to be called `OnWebKitInitialized()`, and this where I am not sure where it should be implemented in cefWork.

I am trying in `Cefgui` by extending 'CefApp and CefRenderProcessHandler`:
'class Cefgui : public CefApp, public CefRenderProcessHandler {...` but I am sure this is the place to do it.

**Comment by ofZach** [comment]
I think this is a really small example that helps
https://github.com/acristoffers/CEF3SimpleSample/tree/master/CEF3SimpleSample

we should probably have an app class (that extends public CefApp, public CefRenderProcessHandler ) like this: 
https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/Independente/ClientApp.h

initialize it like this: 
https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/Mac/AppDelegate.mm#L58

we don't have an app class so our initialization looks like this: 
https://github.com/ofZach/cefWork/blob/master/src/cefGUI/cefgui.cpp#L15

**Comment by ofZach** [comment]
ok I got this working in a primitive way, just need some time to clean it up.  using "settings.single_process = true;" was helpful, I had this problem http://magpcss.org/ceforum/viewtopic.php?f=6&t=5267#p9148

**Comment by smallfly** [comment]
Great!  I did not get it to work before you, but at least I was looking at the correct things (ClientApp class extending CefApp and CefRenderProcessHandler). I hope to be more of help in the next steps.

**Comment by smallfly** [comment]
Hi, do you think you could push these changes, so that I can have a look? Thanks!

**Comment by smallfly** [comment]
I got the JS -> OF communication working. I followed the steps described here. It is pushed here: https://github.com/smallfly/cefWork/tree/feature/JS_to_OF_comm . Did you do it the same way?

I think, next is to be able to have this running without using a single process for the browser and renderer. As we can read this in the header file:

> ... to use a single process for the browser and renderer. This run mode is not officially supported by Chromium and is less stable than the multi-process default.

**Comment by ofZach** [comment]
sorry in midst of work craziness here will take a look when I can.  on first glance this seems really similar to what I did...

**Comment by smallfly** [comment]
Using a single process is definitively not a good thing (see https://github.com/ofZach/cefWork/issues/15).
