### ISSUE TITLE
Crashes when using single_process = true.

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#15]
This is linked to the use of a single process for the browser and renderer (we are using a single process in order to make a 'bridge' between OF and JS - see https://github.com/ofZach/cefWork/issues/13).

**Comment by smallfly** [comment]
I was not able to reproduce this with ofxCEFClient under Windows. It uses also a single process, and it did not crash when loading http://mrdoob.com/#/137/voxels_liquid. Not sure what is the issue on OS X then.

**Comment by smallfly** [comment]
More tests on OS X.

In fact this does not seem to be linked to the use of WebGL or any 'advanced'/heavy HTML/JS stuff. I'm to load http://threejs.org/examples/, and it will crash after loading 2 or 3 of these examples when using a single process.

**Comment by smallfly** [comment]
Ok... I got it. I still need to figure out something. I will pushed some code by tomorrow.

**Comment by smallfly** [comment]
Hi Zach,

It is now working without the need to use a single process. It's pushed on that branch https://github.com/ofZach/cefWork/tree/Fix/OnContextCreated_never_called .

Now I need to find a way to forward the messages received by the 'ClientV8ExtensionHandler'. So far I did it using a pointer to the running 'ofApp':

```
#include "ClientV8ExtensionHandler.h"
#include "ofApp.h"

ClientV8ExtensionHandler::ClientV8ExtensionHandler(CefRefPtr<CefApp> app)
{
    this->app = app;
}

bool ClientV8ExtensionHandler::Execute(const CefString &name, CefRefPtr<CefV8Value> object, const CefV8ValueList &arguments, CefRefPtr<CefV8Value> &retval, CefString &exception)
{
    if (name == "sendDataToOF") {
        if (arguments.size() == 1 && arguments[0]->IsString()) {
            CefString valStr = arguments[0]->GetStringValue();
            
            printf("Got a message from JS!");

            ofApp* ofHostApp = (ofApp*)ofGetAppPtr();
            ofHostApp->gotMessageFromJS(valStr.ToString());
            return true;

         }
    }

    return false;
}
```

But now that the 'process helper' has been updated to the following, it won't building because 'ClientV8ExtensionHandler' includes 'ofApp.h' and therefore OF:

```
#include "include/cef_app.h"
#include "ClientApp.h"

// Entry point function for sub-processes.
int main(int argc, char* argv[]) {
  // Provide CEF with command-line arguments.
  CefMainArgs main_args(argc, argv);

   CefRefPtr<ClientApp> app(new ClientApp);
  // Execute the sub-process.
  return CefExecuteProcess(main_args, app.get(), NULL);
}
```

Do you have an idea of what would be the best way to approach this?

Thanks!

**Comment by ofZach** [comment]
I think the best way to do this is send a message -- this is exactly what the process message stuff is there for. 

on the clientv8 handler: 

            printf("Got a message from JS! \n");

            CefRefPtr<CefProcessMessage> message =
            CefProcessMessage::Create(name);

            CefRefPtr<CefBrowser> browser =
            CefV8Context::GetCurrentContext()->GetBrowser();
            browser->SendProcessMessage(PID_BROWSER, message);

in browser client: 

        bool OnProcessMessageReceived(CefRefPtr<CefBrowser> browser,
                                          CefProcessId source_process,
                                          CefRefPtr<CefProcessMessage> message) {
            cout << "hola" << endl;
            return false;
        }


this seems to work. 

I'm having a lot of trouble with the gitattributes messing up the binary files so it might be good to remove that.   (I think it really wants to stomp over everyones line endings).   I'd push these changes but I want to understand it better.  But with these changes I see stuff getting passed from one thread to another.  And since browserClient is only getting compiled for the main app (not the helper app) it can get some access to OF and pass the message in.

**Comment by smallfly** [comment]
Thanks! It works.

The CefProcessMessage thing was in front of me the all time, and I even tried it but for some reason I did  not get it to work. I guess trying to it with my 14 month old sun on my lap was not a good idea ;)

**Comment by smallfly** [comment]
I pushed and merged into the branch [develop](https://github.com/ofZach/cefWork/tree/develop), a temporary (only strings messages) but working way to handle incoming messages.
