### ISSUE TITLE
Issues with ofTexture while using CEF.

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#17]
Using the ofVideoGrabber example - https://github.com/ofZach/cefWork/tree/fix/ofTexture

The ofTexture are all scramble. This must be linked to the type of texture or the pixel format used by CEF. I quickly tried to enable/disable ARB texture, enable/disable normalized texture, etc... at different place in the ofApp. 

![CEF vs ofTexture](http://smallfly.com/of/cef-ofTexture.png)

@ofZach did you say that you encountered some GL_TEXTURE_2D issues at the beginning when putting cefWork together?

**Comment by ddiakopoulos** [comment]
Possibly something related to glPixelStorei commands

**Comment by smallfly** [comment]
@ddiakopoulos Thanks! Problem solved.

Here is the fix:

```
    GLint swapbytes, lsbfirst, rowlength, skiprows, skippixels, alignment;
    /* Save current pixel store state. */
    
    glGetIntegerv(GL_UNPACK_SWAP_BYTES, &swapbytes);
    glGetIntegerv(GL_UNPACK_LSB_FIRST, &lsbfirst);
    glGetIntegerv(GL_UNPACK_ROW_LENGTH, &rowlength);
    glGetIntegerv(GL_UNPACK_SKIP_ROWS, &skiprows);
    glGetIntegerv(GL_UNPACK_SKIP_PIXELS, &skippixels);
    glGetIntegerv(GL_UNPACK_ALIGNMENT, &alignment);
    
    CefDoMessageLoopWork();
    
    /* Restore current pixel store state. */
    glPixelStorei(GL_UNPACK_SWAP_BYTES, swapbytes);
    glPixelStorei(GL_UNPACK_LSB_FIRST, lsbfirst);
    glPixelStorei(GL_UNPACK_ROW_LENGTH, rowlength);
    glPixelStorei(GL_UNPACK_SKIP_ROWS, skiprows);
    glPixelStorei(GL_UNPACK_SKIP_PIXELS, skippixels);
    glPixelStorei(GL_UNPACK_ALIGNMENT, alignment);
```
