### ISSUE TITLE
.pch file is missing for the cefHelper application

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#2]
A .pch file is missing for the cefHelper application:
clang: error: no such file or directory: '/Users/hugues/Development/openFrameworks/apps/myApps/cefWork/cefHelper/cefHelper-Prefix.pch'

After removing the reference to that file in the building settings of the app, this error goes away, but I want to make sure it's correct to remove it.

**Comment by ofZach** [comment]
this should be fixed now...
