### ISSUE TITLE
Warning: directory not found '...CEF/Release'

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#5]
I get this error:

ld: warning: directory not found for option '-L/Users/hugues/Development/openFrameworks/apps/myApps/cefWork/src/CEF/Release'
ld: warning: directory not found for option '-F/Users/hugues/Development/openFrameworks/apps/myApps/cefWork/src/CEF/Release'
ld: library not found for -lcef_dll_wrapper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This path is defined in the 'Build Settings > Framewroks Search Parths' and in 'Build Settings > Library Search Parths'.

**Comment by ofZach** [comment]
should be fixed now...
