### ISSUE TITLE
library not found for -lcef_dll_wrapper.

### ISSUE THREAD

**Issue by smallfly** [ofZach/cefWork#6]
I can also see a broken reference, to the lib 'libcef_dll_wrapper.a', in the build phases of both the applications (defWork and cefHelper).

**Comment by ofZach** [comment]
still having this issue after the latest commit?  I just re-pulled and all seems to be ok.   it's important to build helper target first than the app in release or debug.

**Comment by smallfly** [comment]
Yes the last commit fixe this. Thanks!
